### ISSUE TITLE
local variable 'psp' referenced before assignment

### ISSUE THREAD

**Issue by xxclouddd** [bvgoncharov/enterprise_warp#3]
in enterprise_warp.py file, line 470

This code seems mistable!

<img width="487" alt="for psp, option in noise_model_dict_psr items()" src="https://user-images.githubusercontent.com/4961377/113850527-26348c80-97cd-11eb-8e7e-2b96638180aa.png">

**Comment by bvgoncharov** [comment]
Hi @xxclouddd , this part handles the addition of pulsar-tailored models to global models and timing models. If I remember correctly, we loop through all pulsar noise terms. We first check if certain pulsar already contains pulsar-specific model, and if so - we add the next one on top. If not, we add it on top of a global model. If the global model doesn't exist, we add it on top of the timing model. Please feel free to suggest improvements! :)
